version: '3'
services:
  jmeter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmeter-container
#    ports:
#      - "60000:60000"
    volumes:
      - ./jmeter-scripts:/jmeter-scripts  # Add your JMeter scripts here
      - ./logs:/logs  # Folder to store logs file
      - ./results:/results  # Folder to store result file
    command: tail -f /dev/null
